<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RealTimeChat.Application\RealTimeChat.Application.csproj" />
    <ProjectReference Include="..\RealTimeChat.Contracts\RealTimeChat.Contracts.csproj" />
    <ProjectReference Include="..\RealTimeChat.Infrastructure\RealTimeChat.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
